"""
Research Report Model
"""

from pydantic import BaseModel, Field


class ResearchReport(BaseModel):
    """
    Final report generated by WriterAgent.
    """

    query: str = Field(
        description="Original user query."
    )

    report: str = Field(
        description="Final markdown research report."
    )

    sources: int = Field(
        default=0,
        description="Number of sources used."
    )