"""
Research Plan Model
"""

from pydantic import BaseModel, Field


class ResearchPlan(BaseModel):
    """
    Output generated by PlannerAgent.
    """

    queries: list[str] = Field(
        description="List of search queries generated by the planner."
    )