"""
Research Context Model
"""

from pydantic import BaseModel, Field


class ResearchContext(BaseModel):
    """
    Output generated by ResearchAgent.
    """

    query: str = Field(
        description="Original user query."
    )

    search_queries: list[str] = Field(
        description="Queries executed during research."
    )

    raw_results: dict = Field(
        description="Raw Tavily search results."
    )

    merged_context: str = Field(
        description="Merged research context."
    )