"""
Pydantic Data Schemas for Nexus AI
"""

from typing import Any, Literal
from pydantic import BaseModel, Field


class SearchResultItem(BaseModel):
    """
    Represents an individual search snippet or retrieved document chunk.
    """

    title: str = Field(description="Title of the source or web page.")
    url: str = Field(
        default="", description="URL of the web source if available."
    )
    content: str = Field(description="Extracted snippet or context text.")
    source_type: Literal["web", "document", "academic"] = Field(
        default="web", description="Type of information source."
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional source metadata."
    )


class ResearchPlan(BaseModel):
    """
    Represents the decomposed research plan generated by the Planner Agent.
    """

    original_query: str = Field(description="Original user research prompt.")
    search_queries: list[str] = Field(
        description="Targeted sub-queries to execute in parallel."
    )
    research_depth: Literal["quick", "standard", "deep"] = Field(
        default="standard", description="Target depth of the research."
    )


class ReflectionAudit(BaseModel):
    """
    Represents the quality audit generated by the Reflection Node.
    """

    is_sufficient: bool = Field(
        default=True,
        description="True if context is sufficient to write report.",
    )
    critique: str = Field(
        description="2-sentence quality critique of search results."
    )
    missing_topics: list[str] = Field(
        default_factory=list,
        description="List of any missing sub-topics or gaps identified.",
    )


class ResearchReport(BaseModel):
    """
    Structured research report generated by the Writer Agent.
    """

    title: str = Field(description="Title of the research report.")
    executive_summary: str = Field(
        description="High-level overview of key insights."
    )
    key_findings: list[str] = Field(
        description="Bullet points of major discoveries and takeaways."
    )
    detailed_analysis: str = Field(
        description="Comprehensive markdown body of the research report."
    )
    sources: list[str] = Field(
        default_factory=list, description="List of source URLs or references used."
    )
    confidence_score: int = Field(
        default=100,
        ge=0,
        le=100,
        description="Confidence score (0-100) of data completeness.",
    )
